"""empty message

Revision ID: 4a6ffffec916
Revises: 32ce76cfb3e4
Create Date: 2018-04-14 12:33:33.985164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6ffffec916'
down_revision = '32ce76cfb3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_answers')
    op.alter_column('possible_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('possible_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('group_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_group_id'], ['question_group.id'], name='group_answers_question_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_answers_pkey')
    )
    # ### end Alembic commands ###
