"""empty message

Revision ID: 6d2a958f300b
Revises: a9e5f1020558
Create Date: 2018-04-14 12:15:00.042791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2a958f300b'
down_revision = 'a9e5f1020558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group_answers', 'question_group', ['question_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_answers', type_='foreignkey')
    # ### end Alembic commands ###
