"""empty message

Revision ID: dab7d03c9bba
Revises: 4a6ffffec916
Create Date: 2018-04-14 12:35:40.326238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab7d03c9bba'
down_revision = '4a6ffffec916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    # ### end Alembic commands ###
